#!/bin/sh

#
echo "starting NeutrinoNG"

until false
do
	/usr/bin/neutrino2
	rtv=$?
	echo "neutrino2 ended <- RTV: " $rtv
	case "$rtv" in
		0) echo "$rtv"
			echo "RESTART"
			sync
			;;
		1) echo "$rtv"
			echo "SHUTDOWN"
			init 0
			;;
		2) echo "$rtv"
			echo "REBOOT"
			init 6
			;;
		*) echo "*"
			echo -e "\033[01;31mERROR: $rtv\033[00m"
			init 6
			;;
	esac
done

