#!/bin/sh

. /etc/profile
echo "[rcS] `date +'%d.%m.%Y %H:%M:%S'` start"
SYSDATE=`date +"%Y%m%d"`

if [ -e /var/etc/.firstboot ]; then
/usr/bin/passwd root <<EOF
root
root
EOF
  rm /var/etc/.firstboot
fi

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t tmpfs tmp /tmp
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

# mdev
echo "[rcS] starting mdev"
echo /sbin/mdev >/proc/sys/kernel/hotplug
mdev -s

echo "[rcS] starting mountall"
/etc/init.d/mountall start

if [ -e /sys/class/net/lo ]; then
	/sbin/ifconfig lo up
fi
if [ -e /sys/class/net/eth0 ]; then
	/sbin/ifconfig eth0 up
fi
if [ -e /sys/class/net/eth1 ]; then
	/sbin/ifconfig eth1 up
fi
if [ -e /sys/class/net/sys0 ]; then
	/sbin/ifconfig sys0 up
fi

echo "[rcS] setup network"
NFS=$(grep -c nfs /proc/cmdline)
if [ "$NFS" -eq "1" ]; then
	echo "Booting from nfs, don't set network"
elif [ -e /var/tuxbox/config/.bootargs ]; then
	echo "using ip set via bootargs, don't reset network"
else
	if [ -e /etc/network/interfaces ]; then
		ip addr flush eth0
		/etc/init.d/networking stop
		#DHCP=$(grep -c dhcp /etc/network/interfaces)
		#if [ "$DHCP" -eq "1" ]; then
		#	echo "Starting dhcp"
		#	/etc/init.d/udhcpc start
		#fi
		/etc/init.d/networking start
	fi
fi
/sbin/ifconfig lo 127.0.0.1 up

# get net-time
(ntpd -n -q -p time.fu-berlin.de) &

/etc/init.d/hostname start
/etc/init.d/portmap start
/usr/sbin/inetd
# rpc.statd for nfs
/etc/init.d/nfs-common start

echo "[rcS] `date +'%d.%m.%Y %H:%M:%S'` load modules"

modprobe hi_media
modprobe hi_mmz
modprobe hi_common
modprobe hi_pdm
modprobe hi_pq
modprobe hi_cipher
modprobe hi_hdmi
modprobe hi_hdmicec
modprobe hi_vou
modprobe hi_gpio
modprobe hi_gpio_i2c i2cmode=2
modprobe hi_i2c
modprobe hi_tde
modprobe hi_otp
modprobe hi_demux
modprobe hi_adec
modprobe hi_vfmw
modprobe hi_vpss
modprobe hi_vdec
modprobe hi_adsp
modprobe hi_aiao
modprobe hi_sync
modprobe hi_pvr
modprobe hi_mce
modprobe hi_tuner
modprobe hi_keyled
modprobe oled
modprobe vtunerc
modprobe hi-dvb hi_vendor=3 hi_device=3
# About hi_fb:
#  For 1920*1080, triple buffer, ARGB8888 format, use:
#  modprobe hi_fb video="hi_fb:vram0_size:16200,vram4_size:2430"
#  For 1280*720, use:
#  modprobe hi_fb video="hi_fb:vram0_size:7200,vram2_size:2430"
#  modprobe hi_fb with no args will use defaule value,The defaule value is set by cfg.mak.
#  vram0 is memory size for HD and vram4 is for SD0. The size is calculated as below:
#  vram0_size = (1920*1080*4*2/1024)KB; vram4_size = (720*576*2*2/1024)KB
modprobe hi_fb
modprobe mali
modprobe hi_dbe
modprobe hi_jpeg
modprobe hi_jpge
modprobe hi_png
modprobe hi_advca
modprobe hi_venc
modprobe hi_aenc
modprobe hi_sci
modprobe hi_vi
modprobe hi_pmoc
modprobe libahci
modprobe libahci_platform
modprobe hisi-ir
modprobe hisi_sci
modprobe hisi_keys
modprobe hisi_encoder

echo 2097152 > /proc/sys/net/core/rmem_max
echo 6 > /proc/sys/vm/dirty_ratio
echo 1 > /proc/sys/vm/overcommit_memory
echo 8192 > /proc/sys/vm/min_free_kbytes
echo 1200000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo interactive > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 200000 > /sys/devices/system/cpu/cpufreq/interactive/timer_rate

wifi=`lsusb | grep -c 0bda:818b`
if [ $wifi  == 1 ]; then
  modprobe cfg80211
  modprobe 8192eu
fi

wifi2=`lsusb | grep -c 0bda:c812`
if [ $wifi2  == 1 ]; then
  modprobe cfg80211
  modprobe 88x2cu
fi

/usr/bin/libreader 720p_50

while [ ! -c /dev/fb0 ]; do
	usleep 100000
done

# set dummy time
NTPDATE=`date +"%Y%m%d"`
if [ "$SYSDATE" == "$NTPDATE" ];then
	date -s "2017-01-01 00:00"
	#date -s "200901011200"
	echo "no ntp-date"
	killall -9 ntpd
	rm -f /tmp/ntpd.pid
else
	echo "[rcS] ntp-date is set > `date +'%d.%m.%Y %H:%M'`"
	rm -f /tmp/ntpd.pid
fi

# rcS.local
if [ -e /var/etc/init.d/rcS.local ]; then 
	/var/etc/init.d/rcS.local
fi

echo "starting NeutrinoNG"

until false
do
	/usr/bin/neutrino2
	rtv=$?
	echo "neutrino2 ended <- RTV: " $rtv
	case "$rtv" in
		0) echo "$rtv"
			echo "RESTART"
			sync
			;;
		1) echo "$rtv"
			echo "SHUTDOWN"
			init 0
			;;
		2) echo "$rtv"
			echo "REBOOT"
			init 6
			;;
		*) echo "*"
			echo -e "\033[01;31mERROR: $rtv\033[00m"
			init 6
			;;
	esac
done

