#!/bin/sh

MODDIR=/lib/modules

insmod $MODDIR/micom.ko
insmod $MODDIR/e2_proc.ko

if [ -e /var/etc/.firstboot ]; then
   rm /var/etc/.firstboot
   sleep 1
   echo "WAIT 3 min"
   /bin/fp_control -t "WAIT 3 min"
   touch /dev/.devfsd
fi

/etc/init.d/mountvirtfs start

if [ -e /dev/ttyAS1 ]; then
   rm -f /dev/ttyAS1
fi

/etc/init.d/portmap start

if [ ! -e /var/etc/.firstboot ]; then
   /bin/fp_control -t "LOADING MODULES"
   echo "LOADING MODULES"

   insmod $MODDIR/stmcore-display-stx7109c3.ko

   echo "init stmfb"
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:yuv:yuv

   echo "load video firmware"
   /bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096
   /bin/ustslave /dev/st231-0 /lib/firmware/video.elf

   echo "load audio firmware"
   /bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096
   /bin/ustslave /dev/st231-1 /lib/firmware/audio.elf

   echo "init embx"
   insmod $MODDIR/embxshell.ko
   insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0xa4000000:0x10000000
   insmod $MODDIR/mme_host.ko transport0=shm

   echo "init AVS"
   insmod $MODDIR/avs.ko type=stv6412
   if [ `lsmod | grep -c "avs"` -eq 0 ]; then
      insmod $MODDIR/avs.ko type=avs_pio
   fi

   echo "init player"
   insmod $MODDIR/mmelog.ko
   insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER1
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/p2div64.ko
   insmod $MODDIR/stm_v4l2.ko
   insmod $MODDIR/pseudocard.ko

   insmod $MODDIR/frontend_platform.ko
   insmod $MODDIR/socket.ko
   insmod $MODDIR/lnbh221.ko
   insmod $MODDIR/lnb_pio.ko
   insmod $MODDIR/dvb-pll.ko
   insmod $MODDIR/cx24116.ko
   insmod $MODDIR/tda10023.ko
   insmod $MODDIR/zl10353.ko
   insmod $MODDIR/stv090x.ko
   insmod $MODDIR/stv0288.ko
   insmod $MODDIR/starci.ko
   insmod $MODDIR/smartcard.ko
   insmod $MODDIR/pti.ko
   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/stmsysfs.ko
   insmod $MODDIR/stmdvb.ko
   insmod $MODDIR/player2.ko discardlateframe=0
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   insmod $MODDIR/silencegen.ko
   insmod $MODDIR/bpamem.ko

   echo "init frontpanel"
   insmod $MODDIR/simu_button.ko
fi

# Module aus modules.extra laden
[ -f /var/etc/modules.extra ] && eval `sed -e 's/#.*//' -e '/^\s*$/d' -e 's/^\(.*\)/insmod \0;/' < /var/etc/modules.extra`

if [ ! -e /var/etc/.firstboot ]; then
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/inetd

   if [ -e /etc/network/interfaces ]; then
     ip addr flush eth0
     /etc/init.d/networking stop
     TEST=$(grep -c 'dhcp' /etc/network/interfaces)
     if [ "$(TEST)" -eq "1" ]; then
       /etc/init.d/udhcpc start
     fi
     /etc/init.d/networking start
   fi

   #timefix
   date -s "200901011200"

   #mdev as hotplug
   echo "[rcS] starting mdev"
   echo /sbin/mdev >/proc/sys/kernel/hotplug
   mdev -s
   # coldplug modules
   find /sys/ -name modalias -print0 | xargs -0 sort -u | tr '\n' '\0' | xargs -0 modprobe -abq

   stfbcontrol a 255

   /bin/evremote2 10 140 &

   /bin/fp_control -l 0 1
    
   # rcS.local
   if [ -e /var/etc/init.d/rcS.local ]; then 
	/var/etc/init.d/rcS.local
   fi
    
   killall -9 showiframe
   
   #
fi

