#!/bin/sh

. /etc/profile

read model < /etc/model

if [ -e /var/etc/.firstboot ]; then
/usr/bin/passwd root <<EOF
root
root
EOF
  rm /var/etc/.firstboot
fi

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t tmpfs tmp /tmp
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

#
echo "[rcS] starting mdev"
echo /sbin/mdev >/proc/sys/kernel/hotplug
mdev -s
# coldplug modules
find /sys/ -name modalias -print0 | xargs -0 sort -u | tr '\n' '\0' | xargs -0 modprobe -abq

echo "starting interface"
/etc/init.d/mountall start

echo "[rcS] loading modules"
modprobe hd60_1
modprobe hd60_2
modprobe hd60_3
modprobe hd60_4

modprobe hi_play

[ -f /lib/modules/$(uname -r)/extra/mali.ko ] && modprobe mali

#
echo "setup network"
/etc/init.d/hostname start
/etc/init.d/portmap start
/usr/sbin/inetd
NFS=$(grep -c nfs /proc/cmdline)
  if [ "$NFS" -eq "1" ]; then
    echo "Booting from nfs, don't set network"
    elif [ -e /var/tuxbox/config/.bootargs ]; then
    echo "using ip set via bootargs, don't reset network"
  else
    if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      /etc/init.d/networking stop
      DHCP=$(grep -c dhcp /etc/network/interfaces)
      if [ "$DHCP" -eq "1" ]; then
        echo "Starting dhcp"
        /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start
    fi
  fi
/sbin/ifconfig lo 127.0.0.1 up

# set dummy time
date -s "2018-01-01 00:00"

# rcS.local
if [ -e /var/etc/rcS.local ]; then 
	/var/etc/rcS.local
fi

echo "[rcS] starting neutrino2 ->"

until false
do
	/usr/bin/neutrino2
	rtv=$?
	echo "neutrino2 ended <- RTV: " $rtv
	case "$rtv" in
		0) echo "$rtv"
			echo "RESTART"
			echo "RESTART" > /dev/dbox/oled0
			sync
			;;
		1) echo "$rtv"
			echo "SHUTDOWN"
			echo "SHUTDOWN" > /dev/dbox/oled0
			init 0
			;;
		2) echo "$rtv"
			echo "REBOOT"
			echo "RBOOT" > /dev/dbox/oled0
			init 6
			;;
		*) echo "*"
			echo -e "\033[01;31mERROR: $rtv\033[00m"
			echo "ERROR: $rtv" > /dev/dbox/oled0
			init 6
			;;
	esac
done

