#!/bin/sh

. /etc/profile

read model < /etc/model

if [ -e /var/etc/.firstboot ]; then
/usr/bin/passwd root <<EOF
root
root
EOF
  rm /var/etc/.firstboot
fi

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t tmpfs tmp /tmp
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

#
echo "[rcS] starting mdev"
echo /sbin/mdev >/proc/sys/kernel/hotplug
mdev -s
# coldplug modules
find /sys/ -name modalias -print0 | xargs -0 sort -u | tr '\n' '\0' | xargs -0 modprobe -abq

echo "starting interface"
/etc/init.d/mountall start

insmod /lib/modules/$(uname -r)/extra/avl6261.ko
insmod /lib/modules/$(uname -r)/extra/avl6862.ko
insmod /lib/modules/$(uname -r)/extra/si2183.ko
insmod /lib/modules/$(uname -r)/extra/ci.ko
insmod /lib/modules/$(uname -r)/extra/brcmstb-osmio4kplus.ko

if [ -e /lib/modules/$(uname -r)/extra/wlan.ko ]; then
  insmod /lib/modules/$(uname -r)/extra/wlan.ko
fi

echo "setup network"
/etc/init.d/hostname start
/etc/init.d/portmap start
/usr/sbin/inetd
NFS=$(grep -c nfs /proc/cmdline)
  if [ "$NFS" -eq "1" ]; then
    echo "Booting from nfs, don't set network"
    elif [ -e /var/tuxbox/config/.bootargs ]; then
    echo "using ip set via bootargs, don't reset network"
  else
    if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      /etc/init.d/networking stop
      DHCP=$(grep -c dhcp /etc/network/interfaces)
      if [ "$DHCP" -eq "1" ]; then
        echo "Starting dhcp"
        /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start
    fi
  fi
/sbin/ifconfig lo 127.0.0.1 up

# set dummy time
date -s "2017-01-01 00:00"

# rcS.local
if [ -e /var/etc/rcS.local ]; then 
	/var/etc/rcS.local
fi

echo "[rcS] starting neutrino ->"

until false
do
	/usr/bin/neutrino
	rtv=$?
	echo "neutrino ended <- RTV: " $rtv
	case "$rtv" in
		0)
		   echo "SHUTDOWN"
		   init 0;;
		1)
		   echo "REBOOT"
		   init 6;;
		3)
		   echo "RESTART";;
		*)
		   echo "ERROR"
		   init 6;;
      	esac
done

