#!/bin/sh

#
echo "starting neutrino-DDT"

until false
do
	/usr/bin/neutrino
	rtv=$?
	echo "GUI ended <- RTV: " $rtv
	case "$rtv" in
		0)
		   echo "SHUTDOWN"
		   init 0;;
		1)
		   echo "REBOOT"
		   init 6;;
		3)
		   echo "RESTART";;
		*)
		   echo "ERROR"
		   init 6;;
      	esac
done

