#!/bin/sh

. /etc/profile
echo "[rcS] `date +'%d.%m.%Y %H:%M:%S'` start"
SYSDATE=`date +"%Y%m%d"`

if [ -e /var/etc/.firstboot ]; then
/usr/bin/passwd root <<EOF
root
root
EOF
  rm /var/etc/.firstboot
fi

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t tmpfs tmp /tmp
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

#
echo "[rcS] starting mdev"
echo /sbin/mdev >/proc/sys/kernel/hotplug
mdev -s
# coldplug modules
find /sys/ -name modalias -print0 | xargs -0 sort -u | tr '\n' '\0' | xargs -0 modprobe -abq

echo "starting interface"
/etc/init.d/mountall start

#
if [ -e /sys/class/net/lo ]; then
	/sbin/ifconfig lo up
fi
if [ -e /sys/class/net/eth0 ]; then
	/sbin/ifconfig eth0 up
fi
if [ -e /sys/class/net/eth1 ]; then
	/sbin/ifconfig eth1 up
fi
if [ -e /sys/class/net/sys0 ]; then
	/sbin/ifconfig sys0 up
fi

if [ ! -e /lib/modules/$(uname -r)/extra/dvb-bcm.ko ]; then
	(cd /lib/modules$(uname -r)/extra/; ln -s dvb-bcm*.ko dvb-bcm.ko)
fi

if [ ! -e /dev/brcm0 ]; then
	if [ -e /usr/bin/bp3flash.sh ]; then
		/usr/bin/bp3flash.sh 2>/dev/null
	fi
	insmod /lib/modules/$(uname -r)/extra/procmk.ko
	insmod /lib/modules/$(uname -r)/extra/bcm_event.ko
	insmod /lib/modules/$(uname -r)/extra/dvb_base.ko
	/usr/bin/dvb_server &
	mknod -m a=rw /dev/brcm0 c 30 0
	/usr/bin/init_client /lib/modules/$(uname -r)/extra/dvb-bcm.ko /lib/modules/$(uname -r)/extra/brcmfb.ko &
fi

while [ ! -c /dev/fb0 ]; do
	usleep 100000
done

echo "setup network"
read hstname < /etc/hostname
if [ "$hstname" == "$model" ]; then
	hwaddr=$(ifconfig eth0 | awk '/HWaddr/ { split($5,v,":"); print v[4] v[5] v[6] }')
	echo "${model}-${hwaddr}" > /etc/hostname
fi
/etc/init.d/hostname start
/etc/init.d/portmap start
/usr/sbin/inetd
NFS=$(grep -c nfs /proc/cmdline)
  if [ "$NFS" -eq "1" ]; then
    echo "Booting from nfs, don't set network"
  else
    if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      /etc/init.d/networking stop
      DHCP=$(grep -c dhcp /etc/network/interfaces)
      if [ "$DHCP" -eq "1" ]; then
        echo "Starting dhcp"
        /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start
    fi
  fi
/sbin/ifconfig lo 127.0.0.1 up

# set dummy time
NTPDATE=`date +"%Y%m%d"`
if [ "$SYSDATE" == "$NTPDATE" ];then
	date -s "2017-01-01 00:00"
	#date -s "200901011200"
	echo "no ntp-date"
	killall -9 ntpd
	rm -f /tmp/ntpd.pid
else
	echo "[rcS] ntp-date is set > `date +'%d.%m.%Y %H:%M'`"
	rm -f /tmp/ntpd.pid
fi

# rcS.local
if [ -e /var/etc/rcS.local ]; then 
	/var/etc/rcS.local
fi

echo "[rcS] starting NeutrinoNG ->"

until false
do
	/usr/bin/neutrino2
	rtv=$?
	echo "neutrino2 ended <- RTV: " $rtv
	case "$rtv" in
		0) echo "$rtv"
			echo "RESTART"
			echo "RESTART" > /dev/dbox/oled0
			sync
			;;
		1) echo "$rtv"
			echo "SHUTDOWN"
			echo "SHUTDOWN" > /dev/dbox/oled0
			init 0
			;;
		2) echo "$rtv"
			echo "REBOOT"
			echo "RBOOT" > /dev/dbox/oled0
			init 6
			;;
		*) echo "*"
			echo -e "\033[01;31mERROR: $rtv\033[00m"
			echo "ERROR: $rtv" > /dev/dbox/oled0
			init 6
			;;
	esac
done

