#!/bin/sh

. /etc/profile

echo "[rcS] `date +'%d.%m.%Y %H:%M:%S'` start"
SYSDATE=`date +"%Y%m%d"`

if [ -e /var/etc/.firstboot ]; then
/usr/bin/passwd root <<EOF
root
root
EOF
  rm /var/etc/.firstboot
fi

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t tmpfs tmp /tmp
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

# mdev
echo "[rcS] starting mdev"
echo /sbin/mdev >/proc/sys/kernel/hotplug
mdev -s
# coldplug modules
find /sys/ -name modalias -print0 | xargs -0 sort -u | tr '\n' '\0' | xargs -0 modprobe -abq

echo "[rcS] starting mountall"
/etc/init.d/mountall start

#
if [ -e /sys/class/net/lo ]; then
	/sbin/ifconfig lo up
fi
if [ -e /sys/class/net/eth0 ]; then
	/sbin/ifconfig eth0 up
fi
if [ -e /sys/class/net/eth1 ]; then
	/sbin/ifconfig eth1 up
fi
if [ -e /sys/class/net/sys0 ]; then
	/sbin/ifconfig sys0 up
fi

#
echo "[rcS] setup network"
NFS=$(grep -c nfs /proc/cmdline)
if [ "$NFS" -eq "1" ]; then
	echo "Booting from nfs, don't set network"
elif [ -e /var/tuxbox/config/.bootargs ]; then
	echo "using ip set via bootargs, don't reset network"
else
	if [ -e /etc/network/interfaces ]; then
		ip addr flush eth0
		/etc/init.d/networking stop
		/etc/init.d/networking start
	fi
fi
/sbin/ifconfig lo 127.0.0.1 up

# get net-time
(ntpd -n -q -p time.fu-berlin.de) &

/etc/init.d/hostname start
/etc/init.d/portmap start
/usr/sbin/inetd
# rpc.statd for nfs
/etc/init.d/nfs-common start

#
echo "[rcS] `date +'%d.%m.%Y %H:%M:%S'` load modules"

#modprobe --force stb-core
#modprobe --force helper
#modprobe --force lcd
#modprobe --force tmp100
#modprobe --force tu1216
#modprobe --force cxd1981
#modprobe --force cu1216mk3
#modprobe --force lnb_ctrl
#modprobe --force si2166b
#modprobe --force si2169c
#modprobe --force bcm4506
#modprobe --force alps_bsbe1
#modprobe --force alps_bsbe1_c01a
#modprobe --force alps_bsbe2
#modprobe --force dreambox_rc2
#modprobe --force dreambox_keyboard
#modprobe --force bcm7405

insmod /lib/modules/$(uname -r)/extra/stb-core.ko
insmod /lib/modules/$(uname -r)/extra/helper.ko
insmod /lib/modules/$(uname -r)/extra/lcd.ko
insmod /lib/modules/$(uname -r)/extra/tmp100.ko
insmod /lib/modules/$(uname -r)/extra/tu1216.ko
insmod /lib/modules/$(uname -r)/extra/cxd1981.ko
insmod /lib/modules/$(uname -r)/extra/cu1216mk3.ko
insmod /lib/modules/$(uname -r)/extra/lnb_ctrl.ko
insmod /lib/modules/$(uname -r)/extra/si2166b.ko
insmod /lib/modules/$(uname -r)/extra/si2169c.ko
insmod /lib/modules/$(uname -r)/extra/bcm4506.ko
insmod /lib/modules/$(uname -r)/extra/alps_bsbe1.ko
insmod /lib/modules/$(uname -r)/extra/alps_bsbe1_c01a.ko
insmod /lib/modules/$(uname -r)/extra/alps_bsbe2.ko
insmod /lib/modules/$(uname -r)/extra/dreambox_rc2.ko
insmod /lib/modules/$(uname -r)/extra/dreambox_keyboard.ko
insmod /lib/modules/$(uname -r)/extra/bcm7405.ko

# set dummy time
NTPDATE=`date +"%Y%m%d"`
if [ "$SYSDATE" == "$NTPDATE" ];then
	date -s "2017-01-01 00:00"
	#date -s "200901011200"
	echo "no ntp-date"
	killall -9 ntpd
	rm -f /tmp/ntpd.pid
else
	echo "[rcS] ntp-date is set > `date +'%d.%m.%Y %H:%M'`"
	rm -f /tmp/ntpd.pid
fi

#
echo 255 > /proc/stb/fp/oled_brightness
echo "Booting... DDT" > /dev/dbox/oled0

until false
do
	echo "[rcS] starting GUI ->"
	/usr/bin/neutrino -v 0
	rtv=$?
	echo "GUI ended <- RTV: " $rtv
	case "$rtv" in
		0) echo "$rtv"
			echo "SHUTDOWN"
			echo "SHUTDOWN" > /dev/dbox/oled0
			init 0
			sleep 20
			;;
		1) echo "$rtv"
			echo "REBOOT"
			echo "REBOOT" > /dev/dbox/oled0
			init 6
			sleep 20
			;;
		3) echo "$rtv"
			echo "RESTART"
			echo "RESTART" > /dev/dbox/oled0
			sync
			;;
		*) echo "*"
			echo -e "\033[01;31mERROR: $rtv\033[00m"
			echo "ERROR: $rtv" > /dev/dbox/oled0
			#init 6
			#sleep 20
			;;
	esac
done

